namespace RaioXVegano.entities.Enum
{
    public enum CodigoRetorno
    {
        EXECUCAO_OK,
        ERRO_GENERICO,
        REQUEST_OBRIGATORIO,
        CHAVE_USUARIO_OBRIGATORIO,
        ID_PRODUTO_OBRIGATORIO,
        PRODUTO_OBRIGATORIO,
        CODIGO_BARRAS_OBRIGATORIO,
        NOME_OBRIGATORIO,
        TIPO_PRODUTO_OBRIGATORIO,
        MOTIVO_OBRIGATORIO,
        PRODUTO_SENDO_EDITADO,
        ERRO_CADASTRO_PRODUTO,
        ERRO_ATUALIZAR_PRODUTO,
        ERRO_CONSULTAR_PRODUTO,
        DATA_LOG_OBRIGATORIO,
        PARAMETRO_1_OBRIGATORIO,
        PARAMETRO_2_OBRIGATORIO,
        ERRO_SALVAR_LOG
    }
}
