//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaioXVegano.entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaioXVegano.entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de preenchimento obrigatório..
        /// </summary>
        public static string campoObrigatorio {
            get {
                return ResourceManager.GetString("campoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no App - Log.
        /// </summary>
        public static string emailAssuntoLogErro {
            get {
                return ResourceManager.GetString("emailAssuntoLogErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudo pronto para você enviar seu e-mail. Siga no seu aplicativo de e-mail para nos enviar os dados e logo você terá noticias nossas. Obrigada! &lt;3.
        /// </summary>
        public static string emailEnviadoComSucesso {
            get {
                return ResourceManager.GetString("emailEnviadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá. &lt;br/&gt;&lt;br/&gt; Recebi um erro no app e gostaria de ajuda. &lt;br/&gt; Meu código usuário é: {0}  (Não apagar o código de usuário) &lt;br/&gt;&lt;br/&gt; Att,.
        /// </summary>
        public static string emailMensagemLogErro {
            get {
                return ResourceManager.GetString("emailMensagemLogErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to raioxvegano@gmail.com.
        /// </summary>
        public static string emailRaioXVegano {
            get {
                return ResourceManager.GetString("emailRaioXVegano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahhh não! Tivemos um problema com a atualização do produto. Tenta mais uma vez e caso o erro continue me manda um e-mail no endereço {0} dizendo o que aconteceu clicando no botão ao lado..
        /// </summary>
        public static string erroAtualizarProduto {
            get {
                return ResourceManager.GetString("erroAtualizarProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahhh não! Tivemos um problema com o cadastro do produto. Tenta mais uma vez e caso o erro continue me manda um e-mail no endereço {0} dizendo o que aconteceu clicando no botão ao lado..
        /// </summary>
        public static string erroCadastrarProduto {
            get {
                return ResourceManager.GetString("erroCadastrarProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahhh não! Tivemos um problema com a consulta do produto. Tenta mais uma vez e caso o erro continue me manda um e-mail no endereço {0} dizendo o que aconteceu clicando no botão ao lado..
        /// </summary>
        public static string erroConsultaProduto {
            get {
                return ResourceManager.GetString("erroConsultaProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahhh não! Tivemos um problema. Tenta mais uma vez e caso o erro continue me manda um e-mail no endereço {0} dizendo o que aconteceu clicando no botão ao lado..
        /// </summary>
        public static string erroGenerico {
            get {
                return ResourceManager.GetString("erroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahhh não! Tivemos um problema com o envio do e-mail. Me manda um e-mail no endereço {0} dizendo o que aconteceu direto do seu aplicativo de e-mail..
        /// </summary>
        public static string erroSalvarLog {
            get {
                return ResourceManager.GetString("erroSalvarLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poxa! Ainda não terminaram de atualizar o produto. Poderia voltar e começar novamente?.
        /// </summary>
        public static string mensagemErroContadorAtualizacao {
            get {
                return ResourceManager.GetString("mensagemErroContadorAtualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem alguém editando o mesmo produto. Espera um pouquinho que vamos atualizar a página para você..
        /// </summary>
        public static string mensagemProdutoSendoEditado {
            get {
                return ResourceManager.GetString("mensagemProdutoSendoEditado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto foi alterado!.
        /// </summary>
        public static string produtoAlteradoSucesso {
            get {
                return ResourceManager.GetString("produtoAlteradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O produto foi cadastrado!.
        /// </summary>
        public static string produtoCadastradoSucesso {
            get {
                return ResourceManager.GetString("produtoCadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não encontramos o produto. Vamos cadastrar?.
        /// </summary>
        public static string produtoNaoEncontrado {
            get {
                return ResourceManager.GetString("produtoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não é vegano!.
        /// </summary>
        public static string produtoNaoVegano {
            get {
                return ResourceManager.GetString("produtoNaoVegano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é vegano!.
        /// </summary>
        public static string produtoVegano {
            get {
                return ResourceManager.GetString("produtoVegano", resourceCulture);
            }
        }
    }
}
